version: '3.8'

services:
  aggregator:
    build: .
    container_name: noblesville-calendar-aggregator
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./output:/app/output
      - ./calendar_cache.db:/app/calendar_cache.db
    environment:
      - EVENTS_URL=https://www.noblesvillemainstreet.org/events
      - UPDATE_INTERVAL=3600  # 1 hour in seconds
      # - UPDATE_INTERVAL=1800  # 30 minutes in seconds
      # - UPDATE_INTERVAL=21600  # 6 hours in seconds
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/merged_calendar.ics"]
      interval: 30s
      timeout: 10s
      retries: 3