services:
  aggregator:
    build: .
    container_name: noblesville-calendar-aggregator
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./output:/app/output
    environment:
      - EVENTS_URL=https://www.noblesvillemainstreet.org/events
      - UPDATE_INTERVAL=3600  # 1 hour in seconds
      # - OUTPUT_DIR=/app/output
    healthcheck:
      test: ["CMD-SHELL", "test -f /app/output/merged_calendar.ics || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s